{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.1.aar",
          "url": "j1939utils-1.1.1.aar",
          "size": 101479,
          "sha512": "e47c9dedf811dce2980ac2f5a4d18abedc1b7ce3d7cebea60a55de7cf2ebb8213668595d4c11486862380b51a39d1a94f3d86a0f1bee5aa1b8ab73e48c1aa250",
          "sha256": "22f93e537a757a8196c2a17f15907ef147e0a83abff0c5bc0daead83dba8244c",
          "sha1": "97d2fdc0a7ab09741af1bfcffcdb96324e3c61e1",
          "md5": "b75aa765868e1234546d3f5018adbeb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.1.aar",
          "url": "j1939utils-1.1.1.aar",
          "size": 101479,
          "sha512": "e47c9dedf811dce2980ac2f5a4d18abedc1b7ce3d7cebea60a55de7cf2ebb8213668595d4c11486862380b51a39d1a94f3d86a0f1bee5aa1b8ab73e48c1aa250",
          "sha256": "22f93e537a757a8196c2a17f15907ef147e0a83abff0c5bc0daead83dba8244c",
          "sha1": "97d2fdc0a7ab09741af1bfcffcdb96324e3c61e1",
          "md5": "b75aa765868e1234546d3f5018adbeb1"
        }
      ]
    }
  ]
}
