{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.2.aar",
          "url": "j1939utils-1.0.2.aar",
          "size": 88105,
          "sha512": "936ff77d3685a1ec3106341dadcdafa5f2c1de64aa61470a39ed908180acdf751bd44e387b90108979ab0478941eedc1e11192b15580ec57b682078719a9649b",
          "sha256": "cd7da9a7f76b1d591bdbf937061b66f5f9e4306ecdcf19c6ab186590a4bf1692",
          "sha1": "54c667c57bb4a5fd2ac233577ebefd398db8e913",
          "md5": "8975d9241e8b28a7ac8383840a85c338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.2.aar",
          "url": "j1939utils-1.0.2.aar",
          "size": 88105,
          "sha512": "936ff77d3685a1ec3106341dadcdafa5f2c1de64aa61470a39ed908180acdf751bd44e387b90108979ab0478941eedc1e11192b15580ec57b682078719a9649b",
          "sha256": "cd7da9a7f76b1d591bdbf937061b66f5f9e4306ecdcf19c6ab186590a4bf1692",
          "sha1": "54c667c57bb4a5fd2ac233577ebefd398db8e913",
          "md5": "8975d9241e8b28a7ac8383840a85c338"
        }
      ]
    }
  ]
}
