{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.0.aar",
          "url": "j1939utils-1.2.0.aar",
          "size": 66489,
          "sha512": "f15157dd89f03f53266c33b4a01c0370c6dcf6f243907e259ccfa262c176a0b4e79185a3986ca91e05750447a49d5b3de3d748ecfef2c58087a0d39e901c2538",
          "sha256": "573b7d5d73591ab71fbedd851793e7284d6c1bfc962a8934ebf518ebbcf49ee4",
          "sha1": "ae00d4ee24f811d9b34714f3dcc1e06fabc51eeb",
          "md5": "5590631f7b7b80d61d292d233c82bc1e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.0.aar",
          "url": "j1939utils-1.2.0.aar",
          "size": 66489,
          "sha512": "f15157dd89f03f53266c33b4a01c0370c6dcf6f243907e259ccfa262c176a0b4e79185a3986ca91e05750447a49d5b3de3d748ecfef2c58087a0d39e901c2538",
          "sha256": "573b7d5d73591ab71fbedd851793e7284d6c1bfc962a8934ebf518ebbcf49ee4",
          "sha1": "ae00d4ee24f811d9b34714f3dcc1e06fabc51eeb",
          "md5": "5590631f7b7b80d61d292d233c82bc1e"
        }
      ]
    }
  ]
}
