{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha.aar",
          "url": "j1939utils-1.0-alpha.aar",
          "size": 79138,
          "sha512": "4b4f8007e0d2131af436e5666e676454e2504ab1553f05892c35e64c59800aa99be665ad505fdde9729dd8455bdd6954064815efebbfa0eb655039081abc1821",
          "sha256": "9fc27ef070227a71b3f9cbf73ea04e32bba6e8fe0a9aacbc810594742c8e0874",
          "sha1": "04d1f5c1d406727a30ddb915f0aec5ff5096e30a",
          "md5": "9f0120ebcb7471df7e1900cbb16b0ff9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha.aar",
          "url": "j1939utils-1.0-alpha.aar",
          "size": 79138,
          "sha512": "4b4f8007e0d2131af436e5666e676454e2504ab1553f05892c35e64c59800aa99be665ad505fdde9729dd8455bdd6954064815efebbfa0eb655039081abc1821",
          "sha256": "9fc27ef070227a71b3f9cbf73ea04e32bba6e8fe0a9aacbc810594742c8e0874",
          "sha1": "04d1f5c1d406727a30ddb915f0aec5ff5096e30a",
          "md5": "9f0120ebcb7471df7e1900cbb16b0ff9"
        }
      ]
    }
  ]
}
