{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.2.aar",
          "url": "j1939utils-1.1.2.aar",
          "size": 94628,
          "sha512": "dc96ccdd04349d6f63153b724cd53b83db44bc4f8a75f51a62fff4c3c700f25e5549b9e23f02bdb831dd43213837bec2c1cf43c0b2864809d284c90034204172",
          "sha256": "2a7da37d4c730c5a0fedb358f40496eb694146c2195ff78bca2d918207f3d30a",
          "sha1": "12409eb560b5494b970d3005714e8dde158e529a",
          "md5": "fdbfb4323ffdb7eab4749afa300f14cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.2.aar",
          "url": "j1939utils-1.1.2.aar",
          "size": 94628,
          "sha512": "dc96ccdd04349d6f63153b724cd53b83db44bc4f8a75f51a62fff4c3c700f25e5549b9e23f02bdb831dd43213837bec2c1cf43c0b2864809d284c90034204172",
          "sha256": "2a7da37d4c730c5a0fedb358f40496eb694146c2195ff78bca2d918207f3d30a",
          "sha1": "12409eb560b5494b970d3005714e8dde158e529a",
          "md5": "fdbfb4323ffdb7eab4749afa300f14cb"
        }
      ]
    }
  ]
}
