{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "custom-wav-player",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-wav-player-1.0.2.aar",
          "url": "custom-wav-player-1.0.2.aar",
          "size": 1416684,
          "sha512": "9cf244d4253739bd86459695b43ee5150e496093288a4b95f22defa5aaed66ea5ffefc09655bb113dfecbd8465eff020067bb5a82bfbc9ef64ad3256576f6828",
          "sha256": "b3a310c7f6282704f164a03e0701ec3fff5184a4857f95bf582ef6ef66b15b81",
          "sha1": "ed33a80c4301959ebc22fcde712efaf2c9480665",
          "md5": "0a55f2941a980b1ff9d0e9a097d7e969"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-wav-player-1.0.2.aar",
          "url": "custom-wav-player-1.0.2.aar",
          "size": 1416684,
          "sha512": "9cf244d4253739bd86459695b43ee5150e496093288a4b95f22defa5aaed66ea5ffefc09655bb113dfecbd8465eff020067bb5a82bfbc9ef64ad3256576f6828",
          "sha256": "b3a310c7f6282704f164a03e0701ec3fff5184a4857f95bf582ef6ef66b15b81",
          "sha1": "ed33a80c4301959ebc22fcde712efaf2c9480665",
          "md5": "0a55f2941a980b1ff9d0e9a097d7e969"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "custom-wav-player-1.0.2-sources.jar",
          "url": "custom-wav-player-1.0.2-sources.jar",
          "size": 2465,
          "sha512": "04cfd0af81249d1a675efeb94e908bb5dd9d806ef489ea07fd5cd51390fc0275d61f5ca17d02f1a89c16b857142be5cd8d1b3aef3175d3096c3b2280b5f9468b",
          "sha256": "517958b93e1fbdbfddfd8d159e9e932b10d07fded08a1eda042b83d9584e90a0",
          "sha1": "6db0b507e4ac8317d6c71e017291c2f8a2caa87c",
          "md5": "950c2cc1a43303b5a79b40c86910585e"
        }
      ]
    }
  ]
}
