{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.0.aar",
          "url": "j1939utils-1.1.0.aar",
          "size": 101364,
          "sha512": "28d67b1977635763a328f3cee8d4fdcc0ee4846b8c4405823c9dbdc643a407f49b890105fdcf91e91aaae5abb75cc6ebb0752eacfea6f88984d7395318565f4a",
          "sha256": "1215945c0d2f68009d7b581ceb6bbc04ebcdeaf29fa41ef4c59e1c50fbec1d51",
          "sha1": "d1be7ebbf97afc8e4480a76d3dc30c537adfa3f9",
          "md5": "58e8eebbc8185a6db8b1639dbd60b990"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.1.0.aar",
          "url": "j1939utils-1.1.0.aar",
          "size": 101364,
          "sha512": "28d67b1977635763a328f3cee8d4fdcc0ee4846b8c4405823c9dbdc643a407f49b890105fdcf91e91aaae5abb75cc6ebb0752eacfea6f88984d7395318565f4a",
          "sha256": "1215945c0d2f68009d7b581ceb6bbc04ebcdeaf29fa41ef4c59e1c50fbec1d51",
          "sha1": "d1be7ebbf97afc8e4480a76d3dc30c537adfa3f9",
          "md5": "58e8eebbc8185a6db8b1639dbd60b990"
        }
      ]
    }
  ]
}
