{
  "formatVersion": "1.1",
  "component": {
    "group": "com.something",
    "module": "dummy-module",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dummy-module-1.0.0.aar",
          "url": "dummy-module-1.0.0.aar",
          "size": 1821,
          "sha512": "04bdbe9653e1a69eaa5a617f827c59e24ed8ce99902a31dbcfd0cca2814bdb50606677d7a3185f9f7e89fbd3a2ca8319e95c8828374efffe77414c7a5cbc06ed",
          "sha256": "20a50aeec7212e0e1d36657e605cfad057c49888b1c43887a137a2736e7ae3d5",
          "sha1": "1f24abc64b3959148ae9eb2d7f56d61c5aa9e9ea",
          "md5": "fcd2b8f53151c2c24b8e12db143e530a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.something",
          "module": "dummy-aar",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "dummy-module-1.0.0.aar",
          "url": "dummy-module-1.0.0.aar",
          "size": 1821,
          "sha512": "04bdbe9653e1a69eaa5a617f827c59e24ed8ce99902a31dbcfd0cca2814bdb50606677d7a3185f9f7e89fbd3a2ca8319e95c8828374efffe77414c7a5cbc06ed",
          "sha256": "20a50aeec7212e0e1d36657e605cfad057c49888b1c43887a137a2736e7ae3d5",
          "sha1": "1f24abc64b3959148ae9eb2d7f56d61c5aa9e9ea",
          "md5": "fcd2b8f53151c2c24b8e12db143e530a"
        }
      ]
    }
  ]
}
