{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.aar",
          "url": "j1939utils-1.0.aar",
          "size": 82043,
          "sha512": "d1f55624d2ac903f34129a277a0be93d3b02d38e576dad5f49a8de224d7653c7652e84a0d04e02a77d11621641361d8d704ae25f2caf289ab6e020d8c07569a2",
          "sha256": "5acc11219785d59c8b2e5a1f529abdf83a76ccf206f77196ea32a4f7a8643d63",
          "sha1": "883c8c26237bd56f6c3b3226d9e7bd12c1a3aae0",
          "md5": "48ea79aad39ae66784ddc20b701433af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.aar",
          "url": "j1939utils-1.0.aar",
          "size": 82043,
          "sha512": "d1f55624d2ac903f34129a277a0be93d3b02d38e576dad5f49a8de224d7653c7652e84a0d04e02a77d11621641361d8d704ae25f2caf289ab6e020d8c07569a2",
          "sha256": "5acc11219785d59c8b2e5a1f529abdf83a76ccf206f77196ea32a4f7a8643d63",
          "sha1": "883c8c26237bd56f6c3b3226d9e7bd12c1a3aae0",
          "md5": "48ea79aad39ae66784ddc20b701433af"
        }
      ]
    }
  ]
}
