{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "softap",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.3"
          }
        }
      ],
      "files": [
        {
          "name": "softap-1.6.1.aar",
          "url": "softap-1.6.1.aar",
          "size": 12142,
          "sha512": "e17b645600e1287ba519b61eb1326e417ce71ca8c82b359182b3e846eafc1443d1057961e6ee8a7ec14842ea0588140e19f98ee5d428e1711b5262de40608b79",
          "sha256": "b1746ec34a0e00643fbaf7569b1ef944d5fdd7c9c46bfbc8925b22f0df30bfc9",
          "sha1": "72ec2d05d99d00c955951b436e2099fcf35232f2",
          "md5": "7d7ee283bd9dd38e790f04af87a70fb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.3"
          }
        }
      ],
      "files": [
        {
          "name": "softap-1.6.1.aar",
          "url": "softap-1.6.1.aar",
          "size": 12142,
          "sha512": "e17b645600e1287ba519b61eb1326e417ce71ca8c82b359182b3e846eafc1443d1057961e6ee8a7ec14842ea0588140e19f98ee5d428e1711b5262de40608b79",
          "sha256": "b1746ec34a0e00643fbaf7569b1ef944d5fdd7c9c46bfbc8925b22f0df30bfc9",
          "sha1": "72ec2d05d99d00c955951b436e2099fcf35232f2",
          "md5": "7d7ee283bd9dd38e790f04af87a70fb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "softap-1.6.1-javadoc.jar",
          "url": "softap-1.6.1-javadoc.jar",
          "size": 276544,
          "sha512": "b8898f3328d8c4f62573b0ce3d2dee18becaf93e8be315398f6e9c6e407c48dc047c58894f2959d855e34790f9d24111c0f57d7f1ac24504d37a15d4815c304d",
          "sha256": "73ae2ee4f80172944841d23b89f0ee0fc38fe872da32848a3c67949375d0ca9e",
          "sha1": "dfd57d994b6159dcb65949b29f40edfd5f0a6fe2",
          "md5": "aa57713e9bd5b8919b6d30954d0e6f5e"
        }
      ]
    }
  ]
}
