{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "softap",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.3"
          }
        }
      ],
      "files": [
        {
          "name": "softap-1.3.aar",
          "url": "softap-1.3.aar",
          "size": 7211,
          "sha512": "4c7ee30d7b71b7816bfb0c722aaa293d89a7b3b8d6515a404f3d3d0de4f47710fb9b990cef0f768d3690be3a3ec56665bf33e889c49fe18b9d3b37e2bc8a96c2",
          "sha256": "af6bbb30a5d5c956d450e6a77c2c6d463fd88ebae7f1ca32179558454c6c33b6",
          "sha1": "90d215abbbc717a3600d9a21de8abfad4f7e4647",
          "md5": "21d55ac59f8a7c5692ba7a9dfb86a825"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linkedin.dexmaker",
          "module": "dexmaker",
          "version": {
            "requires": "2.28.3"
          }
        }
      ],
      "files": [
        {
          "name": "softap-1.3.aar",
          "url": "softap-1.3.aar",
          "size": 7211,
          "sha512": "4c7ee30d7b71b7816bfb0c722aaa293d89a7b3b8d6515a404f3d3d0de4f47710fb9b990cef0f768d3690be3a3ec56665bf33e889c49fe18b9d3b37e2bc8a96c2",
          "sha256": "af6bbb30a5d5c956d450e6a77c2c6d463fd88ebae7f1ca32179558454c6c33b6",
          "sha1": "90d215abbbc717a3600d9a21de8abfad4f7e4647",
          "md5": "21d55ac59f8a7c5692ba7a9dfb86a825"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "softap-1.3-javadoc.jar",
          "url": "softap-1.3-javadoc.jar",
          "size": 268347,
          "sha512": "35aec57fadb1dafeceb994bb5d2c571ae66b9f35b06e65c073e217d590a5ff1b715709cc6b2f0e8a866f8998f1d9b93f908def1cd0504505b4a4acd1574e54d1",
          "sha256": "e6809114bee866bd4bdd4fb772fd201ee7cc4fe2e398583ccee96640ba096877",
          "sha1": "a5ffd6db6d3e8473990989b3ca8af267f3ebe502",
          "md5": "98f375b0fc1bab3a27bbd1cc5d00fa7b"
        }
      ]
    }
  ]
}
