{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.1.aar",
          "url": "j1939utils-1.0.1.aar",
          "size": 86039,
          "sha512": "a618c501a78944dee62a83ac98ea74065a2ebe146abffd7533ce485ad69b0d78748048b48c66600b4fdd84aebf0fc1c463c4d94470f35428b2ef7791784422b2",
          "sha256": "5aea0c77ef74cc4099abf5482f5a52a54a665739f3da7bb052296e984fe51f96",
          "sha1": "6698fdf6273207b6fd364b4000625548566a97a5",
          "md5": "e90adfc8cdd7b72c8f6bd5931492fa7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0.1.aar",
          "url": "j1939utils-1.0.1.aar",
          "size": 86039,
          "sha512": "a618c501a78944dee62a83ac98ea74065a2ebe146abffd7533ce485ad69b0d78748048b48c66600b4fdd84aebf0fc1c463c4d94470f35428b2ef7791784422b2",
          "sha256": "5aea0c77ef74cc4099abf5482f5a52a54a665739f3da7bb052296e984fe51f96",
          "sha1": "6698fdf6273207b6fd364b4000625548566a97a5",
          "md5": "e90adfc8cdd7b72c8f6bd5931492fa7e"
        }
      ]
    }
  ]
}
