{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.1.aar",
          "url": "j1939utils-1.2.1.aar",
          "size": 66955,
          "sha512": "4b45c000e04fcf13fb04853123d57beabafee4ad93f8c0c3ca6b35d04d9590bb428ab05af8968a7e0550a79bd5dcb4ced2999a6062f5efbdf54e889f271b67b8",
          "sha256": "c3fdcaea96a0121ebfb37368d427c4b0c2dff3c293e9efce8459c5283b65d9ec",
          "sha1": "336eb1f4315cbccc646c59e301a839dd80fa9f21",
          "md5": "072271aeec85a711d463d8030f9c6091"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.1.aar",
          "url": "j1939utils-1.2.1.aar",
          "size": 66955,
          "sha512": "4b45c000e04fcf13fb04853123d57beabafee4ad93f8c0c3ca6b35d04d9590bb428ab05af8968a7e0550a79bd5dcb4ced2999a6062f5efbdf54e889f271b67b8",
          "sha256": "c3fdcaea96a0121ebfb37368d427c4b0c2dff3c293e9efce8459c5283b65d9ec",
          "sha1": "336eb1f4315cbccc646c59e301a839dd80fa9f21",
          "md5": "072271aeec85a711d463d8030f9c6091"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j1939utils-1.2.1-javadoc.jar",
          "url": "j1939utils-1.2.1-javadoc.jar",
          "size": 340600,
          "sha512": "420d9bcd834c47a772d4a35759698637cdde19a39d4c6b632b201d1642aa786e36836392094ffaca870ea4f05f8595c85dfd93934da2d7b5bec7c062c0447ecd",
          "sha256": "4d8fa68f5a246d6fe4ef8f20955d84c7475ca929474c63271ce4378f94fd9549",
          "sha1": "28bdd86e756e94ea40afd359a3f8a234e29998ae",
          "md5": "764965d8d0d31281f6a9397d161d3bd9"
        }
      ]
    }
  ]
}
