{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.6.aar",
          "url": "j1939utils-1.2.6.aar",
          "size": 64508,
          "sha512": "dd08758b17a36edd7ed822b4642bf31551acc7dc9ffa0adcbb12052e2fece95bda1e9341984a2a64db808a7838e015ec4a4510771d20e9381234dc833a9a0ab6",
          "sha256": "db45348218ad0543734f6720ab84138eb10a8624dd8dd36610ae9ed019c54f69",
          "sha1": "aa971f91ed8fda8e7ec6e16a7d8ff87f095fe5d0",
          "md5": "ce16c791beaa3d38a64d48a9b7d590d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.2.6.aar",
          "url": "j1939utils-1.2.6.aar",
          "size": 64508,
          "sha512": "dd08758b17a36edd7ed822b4642bf31551acc7dc9ffa0adcbb12052e2fece95bda1e9341984a2a64db808a7838e015ec4a4510771d20e9381234dc833a9a0ab6",
          "sha256": "db45348218ad0543734f6720ab84138eb10a8624dd8dd36610ae9ed019c54f69",
          "sha1": "aa971f91ed8fda8e7ec6e16a7d8ff87f095fe5d0",
          "md5": "ce16c791beaa3d38a64d48a9b7d590d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "j1939utils-1.2.6-javadoc.jar",
          "url": "j1939utils-1.2.6-javadoc.jar",
          "size": 347523,
          "sha512": "be532d768057798b8d4558abd6b105f65579e153c2ebc17cf8f5959fed601c54da93a9f952a6329d5489548e2bb39637f9a250d8fde745fd0ec4db3268f8117f",
          "sha256": "3e7ffe8692ff67adaa571068eb7044b648a4453754c866f4637eb7273ca6838f",
          "sha1": "800d1962772e48a67f0619c765e5d1c88d49baec",
          "md5": "08dc90c9200345b2a92bc4f4e95de35a"
        }
      ]
    }
  ]
}
