{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "custom-tone-maker",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-tone-maker-1.0.2.aar",
          "url": "custom-tone-maker-1.0.2.aar",
          "size": 1225592,
          "sha512": "2fa40648d4da9f1bebbf9cf0192c585fda417e405cddc1a2fb28bf6c14893a1526df95c4aef318235a9a8d0c1c0d1b5606ae7be852ae5f310de84bc359ca2763",
          "sha256": "61e7a382f0f1c0e3a24ad60167f6976237d0e9f3504fd47a679712293a775ea2",
          "sha1": "5a14cde5c6e4d3625d1355c2b6dddb117042c090",
          "md5": "53efb4e916fe32dfc294274fb367707c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-tone-maker-1.0.2.aar",
          "url": "custom-tone-maker-1.0.2.aar",
          "size": 1225592,
          "sha512": "2fa40648d4da9f1bebbf9cf0192c585fda417e405cddc1a2fb28bf6c14893a1526df95c4aef318235a9a8d0c1c0d1b5606ae7be852ae5f310de84bc359ca2763",
          "sha256": "61e7a382f0f1c0e3a24ad60167f6976237d0e9f3504fd47a679712293a775ea2",
          "sha1": "5a14cde5c6e4d3625d1355c2b6dddb117042c090",
          "md5": "53efb4e916fe32dfc294274fb367707c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-tone-maker-1.0.2-javadoc.jar",
          "url": "custom-tone-maker-1.0.2-javadoc.jar",
          "size": 260397,
          "sha512": "cb62ea329fb55171f99f619618cb5302d0f942d081df26a6d53380cb453bccc04b3378abb4ed36bfb789aec8b176ad1313a1728699532d4463f465050ab42878",
          "sha256": "aec9fc2842e8f83c643bd2c0f966c99e36a797cf066d229da8c4eb9362c353b9",
          "sha1": "05ce0e0ce21cad480c834f6f382441b5a54a4413",
          "md5": "649aeb6eb6c51433349fd15ec1fa913c"
        }
      ]
    }
  ]
}
