{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "custom-tone-maker",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-tone-maker-1.0.aar",
          "url": "custom-tone-maker-1.0.aar",
          "size": 1223994,
          "sha512": "400fc21fe302bc56db7cad14dc73194ad7509ddcf48e013a8751814d930d3469478d75f5c5e1385d487c335bd2a80c26aaeb363e2033885651ad56d2ff977b99",
          "sha256": "39e97ca9310316960b97d5728dedb66c40ec8753f17d9b8d78e40eb6b3dee4fa",
          "sha1": "aaf7ee9398187326339e2175ac110b5d9c707479",
          "md5": "e69e33d36bfe5dce8838323ef7abea79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "custom-tone-maker-1.0.aar",
          "url": "custom-tone-maker-1.0.aar",
          "size": 1223994,
          "sha512": "400fc21fe302bc56db7cad14dc73194ad7509ddcf48e013a8751814d930d3469478d75f5c5e1385d487c335bd2a80c26aaeb363e2033885651ad56d2ff977b99",
          "sha256": "39e97ca9310316960b97d5728dedb66c40ec8753f17d9b8d78e40eb6b3dee4fa",
          "sha1": "aaf7ee9398187326339e2175ac110b5d9c707479",
          "md5": "e69e33d36bfe5dce8838323ef7abea79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-tone-maker-1.0-javadoc.jar",
          "url": "custom-tone-maker-1.0-javadoc.jar",
          "size": 260213,
          "sha512": "3f778117214a213d51c1f25c650d27ff293cab3c4488d02a08a9912301f673080e59ee033ff6cf1e923f5147f72b07f4aeef29aa15514485a5ae182c00e667bd",
          "sha256": "979030caceeeb277a16ede4109703ae1d708d775ecf5b054a7e820075b9eb68f",
          "sha1": "c263f1995fcd9a0a0288b9dcf2094cdc139adb6b",
          "md5": "8d82291fac10cc1f803d2fde03c16e7c"
        }
      ]
    }
  ]
}
