{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0-alpha3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha3.aar",
          "url": "j1939utils-1.0-alpha3.aar",
          "size": 82016,
          "sha512": "ffb37780c47cd19af4e02815420e727af5da4213bd0c3bf7fcfd26b2e4eecbcbc0fc55d9befc81368deb54fdf2f1e026d7b2ff5f1ca3dfde559a33d50f5a1ae1",
          "sha256": "6c1673786353e23819b3dc8c9220f0c7b92aedb93d2e143e0d9398e1d37a233b",
          "sha1": "d90fcf6c1135e7e2b7031b9d63a1974278901cc7",
          "md5": "021dcd2cc9b631bfacf567175ac04ae7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha3.aar",
          "url": "j1939utils-1.0-alpha3.aar",
          "size": 82016,
          "sha512": "ffb37780c47cd19af4e02815420e727af5da4213bd0c3bf7fcfd26b2e4eecbcbc0fc55d9befc81368deb54fdf2f1e026d7b2ff5f1ca3dfde559a33d50f5a1ae1",
          "sha256": "6c1673786353e23819b3dc8c9220f0c7b92aedb93d2e143e0d9398e1d37a233b",
          "sha1": "d90fcf6c1135e7e2b7031b9d63a1974278901cc7",
          "md5": "021dcd2cc9b631bfacf567175ac04ae7"
        }
      ]
    }
  ]
}
