{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.lib",
    "module": "j1939utils",
    "version": "1.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha1.aar",
          "url": "j1939utils-1.0-alpha1.aar",
          "size": 79310,
          "sha512": "f90c262baf690d1531b46ce7572217bdb72da18ec716bc608a2c05a9219124c80bc3144200b1a84885af75d7f3eddc8889c0013ddbdefbd274ab36f09e16bdc7",
          "sha256": "21bc2c6b7252e4642bbb363166031441bc78cbcd9653b18f03a4aa290616e4ac",
          "sha1": "fdb523f32477a361c8cad395b681015a6fe775c3",
          "md5": "cb49051db723a393e6160f1de3a9e312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "j1939utils-1.0-alpha1.aar",
          "url": "j1939utils-1.0-alpha1.aar",
          "size": 79310,
          "sha512": "f90c262baf690d1531b46ce7572217bdb72da18ec716bc608a2c05a9219124c80bc3144200b1a84885af75d7f3eddc8889c0013ddbdefbd274ab36f09e16bdc7",
          "sha256": "21bc2c6b7252e4642bbb363166031441bc78cbcd9653b18f03a4aa290616e4ac",
          "sha1": "fdb523f32477a361c8cad395b681015a6fe775c3",
          "md5": "cb49051db723a393e6160f1de3a9e312"
        }
      ]
    }
  ]
}
